// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5tRoXK9Rc0pyrmL5VdykTZdlMgCFfKk0',
    appId: '1:820294367760:android:c77db5f8b830e6c9556895',
    messagingSenderId: '820294367760',
    projectId: 'roadmate-fb5b4',
    storageBucket: 'roadmate-fb5b4.firebasestorage.app',
  );

  /// iOS Firebase config.
  ///
  /// Fill these values from your Firebase iOS app settings.
  /// Easiest: open `ios/Runner/GoogleService-Info.plist` and copy:
  ///  - API_KEY -> apiKey
  ///  - GOOGLE_APP_ID -> appId
  ///  - GCM_SENDER_ID -> messagingSenderId
  ///  - PROJECT_ID -> projectId
  ///  - STORAGE_BUCKET -> storageBucket (if present)
  /// And set `iosBundleId` to your iOS bundle id (e.g. `com.roadMate.ai`).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQczIhJfepxEguBHV7pB8UGTBjEEOh2mE',
    appId: '1:820294367760:ios:82990ed7d53dde71556895',
    messagingSenderId: '820294367760',
    projectId: 'roadmate-fb5b4',
    storageBucket: 'roadmate-fb5b4.firebasestorage.app',
    iosBundleId: 'com.roadMate.ai',
  );
}
